version: '3'

services:
  pg-tasks:
    image: postgres:9.6
    container_name: pg-tasks
    restart: always
    ports:
      - 5433:5432

    environment:
      - POSTGRES_DB=tasks
      - POSTSGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust